# Generated by Django 5.2.17 on 2026-09-24 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic', '0002_initial'),
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendanceexceptionlog',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendanceexceptionlog',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academic.department'),
        ),
        migrations.AddField(
            model_name='facultysubstitution',
            name='absent_faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions_as_absent', to='academic.facultyprofile'),
        ),
        migrations.AddField(
            model_name='facultysubstitution',
            name='assigned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facultysubstitution',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='substitution_record', to='academic.classsession'),
        ),
        migrations.AddField(
            model_name='facultysubstitution',
            name='substitute_faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions_as_substitute', to='academic.facultyprofile'),
        ),
    ]
