# Generated by Django 5.2.17 on 2026-09-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceCorrectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_status', models.CharField(max_length=15)),
                ('new_status', models.CharField(max_length=15)),
                ('reason', models.TextField(help_text='Mandatory audit justification for the correction')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('EXCUSED', 'Excused')], default='PRESENT', max_length=15)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FacultyBiometricLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punch_time', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('LATE', 'Late'), ('ABSENT', 'Absent')], default='PRESENT', max_length=15)),
                ('device_id', models.CharField(default='BIO-GATE-01', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', 'faculty'],
            },
        ),
    ]
