# Generated by Django 5.2.17 on 2026-09-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_label', models.CharField(help_text='e.g. 2026-2027', max_length=20, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('designation', models.CharField(help_text='e.g. Student Records Administrator, Academic Administration Officer', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField(db_index=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('topic', models.CharField(blank=True, max_length=255)),
                ('is_attendance_taken', models.BooleanField(db_index=True, default=False)),
                ('attendance_taken_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-session_date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FacultyAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['faculty', 'subject'],
            },
        ),
        migrations.CreateModel(
            name='FacultyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_id', models.CharField(db_index=True, help_text='e.g. FAC-CSE-001', max_length=50, unique=True)),
                ('designation', models.CharField(default='Assistant Professor', max_length=100)),
                ('is_hod', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['faculty_id'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. CSE-1, CSE-2', max_length=50)),
                ('current_semester', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'ordering': ['department', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(help_text='1 to 8')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['academic_year', 'number'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(db_index=True, help_text='e.g. STU-CSE1-0001', max_length=50, unique=True)),
                ('semester', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'ordering': ['student_id'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=30, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('semester', models.PositiveSmallIntegerField(help_text='Applicable semester number (1-8)')),
                ('credits', models.PositiveSmallIntegerField(default=3)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
    ]
