# Generated by Django 5.2.17 on 2026-09-24 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='counsellor',
            field=models.ForeignKey(blank=True, help_text='Faculty member designated as the Section Counsellor / Proctor', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counselled_sections', to='academic.facultyprofile'),
        ),
    ]
